db:
  name: 'test.db'
  data_root: ''

editor:
  max_utterance: 5

tts:
  seed: 42
  candidates: 1
  spkr_emb_sample_rate: 22_050
  sample_rate: 24_000
  num_autoregressive_samples: 16
  preset: ???
  playground:
    candidates: 4

stt:
  sample_rate: 16_000
  model_size: large
  half_precision: False

diarization:
  model_name: "pyannote/speaker-diarization@2.1"
  auth_token: "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"

translation:
  auth_token: "ec035bdb-9e90-810f-cfd3-2da51ee91ca2:fx"

podcastindex:
  api_key: "8SKFTZXBN83JEX5M99UX"
  api_secret: "YRteGrQ5HG4F4C8dk9HJQz8DzkPnDkKbuGsA5##G"
  db:
    name: "podcastindex_feeds.db"

demo:
  duration_sec: 120
  extra_dur_sec: 2
  ad_offset_sec: 120