db:
  name: 'test.db'
  data_root: './user_data'

editor:
  max_utterance: 40

tts:
  seed: 42
  candidates: 1
  sample_rate: 24_000

stt:
  sample_rate: 16_000
  model_size: large

diarization:
  model_name: "pyannote/speaker-diarization@2.1"
  auth_token: "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"
